id: P000146
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ཞེན་བཟློག་ཉེར་ལྔའི་འགྲེལ་བ། རྡོ་རྗེའི་ཚིག་གི་མདུད་དཀྲོལ་ལ་སོགས།
  authors:
  - མཛད་པ་པོ། ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  layers:
  - book_title
  - author
  - yigchung
  id: SHE-DKR-11
web_metadata:
  title:
    en: A Commentary on the Twenty-Five Modes of Reversing Attachment, Including the
      Explanation of the Meaning of Vajra Words
    bo: ཞེན་བཟློག་ཉེར་ལྔའི་འགྲེལ་བ། རྡོ་རྗེའི་ཚིག་གི་མདུད་དཀྲོལ་ལ་སོགས།
  collection:
    en: Dilgo Khyentse Series–  Book 11
    bo: དིལ་མགོ་མཁྱེན་བཙེ་གསུང་འབུམ།–  དེབ། ༡༡
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-DKR-11
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-DKR-11.epub
  description:
    en: ''
    bo: ''
